# Generated by Django 3.0.7 on 2020-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50, null=True)),
                ('precio', models.IntegerField()),
                ('talla', models.CharField(max_length=15, null=True)),
                ('color', models.CharField(max_length=25)),
                ('descripcion', models.TextField(null=True)),
                ('imagen', models.ImageField(null=True, upload_to='uploads/')),
            ],
        ),
    ]
