# Generated by Django 3.0.7 on 2020-06-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='apellido_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='email_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='password',
            new_name='password_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='username',
            new_name='username_cliente',
        ),
    ]
