# Generated by Django 3.0.7 on 2020-06-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200622_0221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
